<#
.SYNOPSIS
  Installs git pre-commit and pre-push hooks for the Public-html-pages repository.
.EXAMPLE
  .\tools\install-hooks.ps1
#>
[CmdletBinding()]
param()
$ErrorActionPreference = "Stop"
$repoRoot = (Get-Item $PSScriptRoot).Parent.FullName
$hookDir = Join-Path $repoRoot ".git\hooks"
if (-not (Test-Path $hookDir)) {
    Write-Host "ERROR: .git\hooks not found. Run from inside the git repository." -ForegroundColor Red
    exit 1
}
$checkerPath = Join-Path $repoRoot "tools\pre-publish-check.ps1"
if (-not (Test-Path $checkerPath)) {
    Write-Host "ERROR: tools\pre-publish-check.ps1 not found." -ForegroundColor Red
    exit 1
}

$preCommit = @"
#!/bin/sh
# Auto-generated by tools/install-hooks.ps1
POWERSHELL_CMD="powershell.exe -NoProfile -ExecutionPolicy Bypass"
CHECKER="tools/pre-publish-check.ps1"
STAGED_HTML=`$(git diff --cached --name-only --diff-filter=ACM | grep -i '\.html`$')
if [ -z "`$STAGED_HTML" ]; then exit 0; fi
echo "=== Pre-Publication Security Check (staged HTML) ==="
HAS_ERRORS=0
for FILE in `$STAGED_HTML; do
    if [ -f "`$FILE" ]; then
        `$POWERSHELL_CMD -File "`$CHECKER" -Path "`$FILE" -CheckOnly 2>&1
        if [ `$? -ne 0 ]; then HAS_ERRORS=1; fi
    fi
done
if [ `$HAS_ERRORS -ne 0 ]; then
    echo "SECURITY CHECK FAILED. Fix errors before committing."
    echo "To bypass: git commit --no-verify"
    exit 1
fi
echo "Security check passed for staged HTML files."
exit 0
"@

$prePush = @"
#!/bin/sh
# Auto-generated by tools/install-hooks.ps1
POWERSHELL_CMD="powershell.exe -NoProfile -ExecutionPolicy Bypass"
CHECKER="tools/pre-publish-check.ps1"
echo "=== Pre-Push Security Check (full repository) ==="
`$POWERSHELL_CMD -File "`$CHECKER" -FailOnWarning 2>&1
if [ `$? -ne 0 ]; then
    echo "SECURITY CHECK FAILED. Fix issues before pushing."
    echo "To bypass: git push --no-verify"
    exit 1
fi
echo "Full repository security check passed."
exit 0
"@

$preCommitPath = Join-Path $hookDir "pre-commit"
$prePushPath   = Join-Path $hookDir "pre-push"
$preCommit | Set-Content -Path $preCommitPath -Encoding UTF8 -NoNewline
$prePush   | Set-Content -Path $prePushPath   -Encoding UTF8 -NoNewline
try { & chmod +x $preCommitPath 2>$null } catch {}
try { & chmod +x $prePushPath 2>$null } catch {}
Write-Host "Installed git hooks:" -ForegroundColor Green
Write-Host "  $preCommitPath" -ForegroundColor DarkGray
Write-Host "  $prePushPath"   -ForegroundColor DarkGray
Write-Host ""
Write-Host "pre-commit:  Scans staged .html files (fast, per-file)" -ForegroundColor Cyan
Write-Host "pre-push:    Full repository scan with -FailOnWarning" -ForegroundColor Cyan
Write-Host ""
Write-Host "To bypass:    git commit --no-verify / git push --no-verify"
Write-Host "To uninstall: Remove .git\hooks\pre-commit and pre-push"